spring.application.name=vendor-management-system


# ---------------- JSP CONFIGURATION ----------------

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp



# ---------------- DATABASE CONFIGURATION ----------------

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}



# ---------------- HIBERNATE CONFIGURATION ----------------

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true



# ---------------- SERVER PORT ----------------

server.port=${PORT:8080}



# ---------------- SPRING SECURITY ----------------

spring.security.user.name=akher

spring.security.user.password=123



# GITHUB OAUTH

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
